backend/config/routes.rb
InterestMatch::Application.routes.draw do
  resources :cateroties

  get "welcome/index"
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' }
  resources :interests

  root 'welcome#index'

end

backend/app/models/cateroty.rb
class Cateroty < ActiveRecord::Base
  has_many :interests
end

backend/app/models/interest.rb
class Interest < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

backend/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  has_many :interests
  accepts_nested_attributes_for :interests, allow_destroy: true

  def full_name
    if name.present?
      name
    else
      "#{first_name} #{last_name}"
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
    end
    user
  end

end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :set_access_control_headers
	skip_before_filter :verify_authenticity_token
  private

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end

end

backend/app/controllers/cateroties_controller.rb
class CaterotiesController < ApplicationController
  before_action :set_cateroty, only: [:show, :edit, :update, :destroy]

  # GET /cateroties
  # GET /cateroties.json
  def index
    @cateroties = Cateroty.all
  end

  # GET /cateroties/1
  # GET /cateroties/1.json
  def show
  end

  # GET /cateroties/new
  def new
    @cateroty = Cateroty.new
  end

  # GET /cateroties/1/edit
  def edit
  end

  # POST /cateroties
  # POST /cateroties.json
  def create
    @cateroty = Cateroty.new(cateroty_params)

    respond_to do |format|
      if @cateroty.save
        format.html { redirect_to @cateroty, notice: 'Cateroty was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cateroty }
      else
        format.html { render action: 'new' }
        format.json { render json: @cateroty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cateroties/1
  # PATCH/PUT /cateroties/1.json
  def update
    respond_to do |format|
      if @cateroty.update(cateroty_params)
        format.html { redirect_to @cateroty, notice: 'Cateroty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cateroty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cateroties/1
  # DELETE /cateroties/1.json
  def destroy
    @cateroty.destroy
    respond_to do |format|
      format.html { redirect_to cateroties_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cateroty
      @cateroty = Cateroty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cateroty_params
      params.require(:cateroty).permit(:name)
    end
end

backend/app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy]

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render action: 'show', status: :created, location: @interest }
      else
        format.html { render action: 'new' }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:name, :description, :lat, :lon, :user_id)
    end
end

backend/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = '11111111111'
    

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :phone, :skype, :age, :gender, :lat, :lon, :name)
    end
end

backend/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/cateroties_helper.rb
module CaterotiesHelper
end

backend/app/helpers/interests_helper.rb
module InterestsHelper
end

backend/app/helpers/users_helper.rb
module UsersHelper
end

backend/app/helpers/welcome_helper.rb
module WelcomeHelper
end

backend/app/views/cateroties/_form.html.haml
= form_for @cateroty do |f|
  - if @cateroty.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cateroty.errors.count, "error")} prohibited this cateroty from being saved:"
      %ul
        - @cateroty.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

backend/app/views/cateroties/edit.html.haml
%h1 Editing cateroty

= render 'form'

= link_to 'Show', @cateroty
\|
= link_to 'Back', cateroties_path

backend/app/views/cateroties/index.html.haml
%h1 Listing cateroties

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @cateroties.each do |cateroty|
    %tr
      %td= cateroty.name
      %td= link_to 'Show', cateroty
      %td= link_to 'Edit', edit_cateroty_path(cateroty)
      %td= link_to 'Destroy', cateroty, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Cateroty', new_cateroty_path

backend/app/views/cateroties/new.html.haml
%h1 New cateroty

= render 'form'

= link_to 'Back', cateroties_path

backend/app/views/cateroties/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @cateroty.name

= link_to 'Edit', edit_cateroty_path(@cateroty)
\|
= link_to 'Back', cateroties_path

backend/app/views/interests/_form.html.erb
<%= form_for(@interest) do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.order(:first_name, :last_name), :id, :full_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/interests/edit.html.erb
<h1>Editing interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

backend/app/views/interests/index.html.erb
<h1>Listing interests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.name %></td>
        <td><%= interest.description %></td>
        <td><%= interest.lat %></td>
        <td><%= interest.lon %></td>
        <td><%= interest.user.full_name rescue nil %></td>
        <td><%= link_to 'Show', interest %></td>
        <td><%= link_to 'Edit', edit_interest_path(interest) %></td>
        <td><%= link_to 'Destroy', interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest', new_interest_path %>

backend/app/views/interests/new.html.erb
<h1>New interest</h1>

<%= render 'form' %>

<%= link_to 'Back', interests_path %>

backend/app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @interest.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @interest.description %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @interest.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @interest.lon %>
</p>

<p>
  <strong>User:</strong>
  <%= @interest.user.full_name rescue nil %> 
</p>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>

backend/app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/

    -#%link{:href => "../../docs-assets/ico/favicon.png", :rel => "shortcut icon"}/

    %title Interest Match

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    -#%link{:href => "sticky-footer-navbar.css", :rel => "stylesheet"}/
    = javascript_include_tag "application", "data-turbolinks-track" => true

    / Just for debugging purposes. Don't actually copy this line!
    /[if lt IE 9] <script src="../../docs-assets/js/ie8-responsive-file-warning.js"></script>
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

  = csrf_meta_tags

  %body
    / Wrap all page content here
    #wrap
      / Fixed navbar
      .navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
        .container
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{:href => "#"} Interest Match
          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.active
                %a{:href => "#"} Home
              %li
                %a{:href => "#about"} About
              %li
                %a{:href => "#contact"} Contact
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Dropdown
                  %b.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "#"} Action
                  %li
                    %a{:href => "#"} Another action
                  %li
                    %a{:href => "#"} Something else here
                  %li.divider
                  %li.dropdown-header Nav header
                  %li
                    %a{:href => "#"} Separated link
                  %li
                    %a{:href => "#"} One more separated link
            - if user_signed_in?
              %ul.nav.navbar-nav.pull-right
                %li= link_to current_user.full_name, '#'

		
          / /.nav-collapse
      / Begin page content
      .container

        = yield
 
    #footer
      .container
        %p.text-muted &copy; HackerDojo Team. Bala, Jun, Mike, Vlad, Yura.
    /
      Bootstrap core JavaScript
      \==================================================
    / Placed at the end of the document so the pages load faster

backend/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :skype %><br>
    <%= f.text_field :skype %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.select :gender, [ [ 'Female', 1 ], [ 'Male', 2 ] ], include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

backend/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Skype</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Lat</th>
      <th>Lon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.skype %></td>
        <td><%= user.age %></td>
        <td><%= user.gender %></td>
        <td><%= user.lat %></td>
        <td><%= user.lon %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div id="create_interest"></div>
<br>

<%= link_to 'New User', new_user_path %>

backend/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

backend/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Skype:</strong>
  <%= @user.skype %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @user.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @user.lon %>
</p>

<h2>Interests</h2>


<table>
  <tr>
    <th>Interest</th>
    <th>Description</th>
  </tr>
  <% @user.interests.each do |interest| %>
    <tr>
      <td><%= interest.name %></td>
      <td><%= interest.description %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

backend/app/views/welcome/_interests.html.haml
%h1 My [offline] interests

backend/app/views/welcome/_welcome.html.haml
.jumbotron
  .page-header
    %h1 
      %sup{ class: 'text-success' } [offline] 
      Social Networking

  %p.lead
    We hate to play table tennis, pool and have dinners online! Join us and meet you offline!
  %p
    = link_to "Join us using Facebook", user_omniauth_authorize_path(:facebook), class: 'btn btn-lg btn-success'

backend/app/views/welcome/index.html.haml
- if user_signed_in?
  = render 'interests'
- else
  = render 'welcome'